src/Entity/Episode.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EpisodeRepository")
 */
class Episode
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_original;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $numero_episode;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $numero_production;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $premiere_diffusion;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $duree;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Saison", inversedBy="episodes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $saison;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EpisodePersonne", mappedBy="episode")
     */
    private $episodePersonnes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Personne", mappedBy="episode_favori")
     */
    private $personnes;

    public function __construct()
    {
        $this->episodePersonnes = new ArrayCollection();
        $this->personnes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTitreOriginal(): ?string
    {
        return $this->titre_original;
    }

    public function setTitreOriginal(string $titre_original): self
    {
        $this->titre_original = $titre_original;

        return $this;
    }
    
    public function getTitreComplet($vo){
        if(is_null($this->titre)){
            return $this->titre_original;
        } else if($vo){
            return $this->titre_original;
        } else {
            return $this->titre;
        }
    }

    public function getNumeroEpisode(): ?int
    {
        return $this->numero_episode;
    }

    public function setNumeroEpisode(int $numero_episode): self
    {
        $this->numero_episode = $numero_episode;

        return $this;
    }

    public function getNumeroProduction(): ?int
    {
        return $this->numero_production;
    }

    public function setNumeroProduction(int $numero_production): self
    {
        $this->numero_production = $numero_production;

        return $this;
    }

    public function getPremiereDiffusion(): ?\DateTimeInterface
    {
        return $this->premiere_diffusion;
    }

    public function setPremiereDiffusion(?\DateTimeInterface $premiere_diffusion): self
    {
        $this->premiere_diffusion = $premiere_diffusion;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSaison(): ?Saison
    {
        return $this->saison;
    }

    public function setSaison(?Saison $saison): self
    {
        $this->saison = $saison;

        return $this;
    }

    /**
     * @return Collection|EpisodePersonne[]
     */
    public function getEpisodePersonnes(): Collection
    {
        return $this->episodePersonnes;
    }

    public function addEpisodePersonne(EpisodePersonne $episodePersonne): self
    {
        if (!$this->episodePersonnes->contains($episodePersonne)) {
            $this->episodePersonnes[] = $episodePersonne;
            $episodePersonne->setEpisode($this);
        }

        return $this;
    }

    public function removeEpisodePersonne(EpisodePersonne $episodePersonne): self
    {
        if ($this->episodePersonnes->contains($episodePersonne)) {
            $this->episodePersonnes->removeElement($episodePersonne);
            // set the owning side to null (unless already changed)
            if ($episodePersonne->getEpisode() === $this) {
                $episodePersonne->setEpisode(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setEpisodeFavori($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->contains($personne)) {
            $this->personnes->removeElement($personne);
            // set the owning side to null (unless already changed)
            if ($personne->getEpisodeFavori() === $this) {
                $personne->setEpisodeFavori(null);
            }
        }

        return $this;
    }
}

src/Entity/Saison.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SaisonRepository")
 */
class Saison
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;
    
    /**
     * @ORM\Column(type="smallint")
     */
    private $numero_saison;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_episode;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Serie", inversedBy="saisons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serie;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Photo", inversedBy="saisons")
     */
    private $photo;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActeurSaison", mappedBy="saison")
     */
    private $acteurSaisons;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="saison")
     * @ORM\OrderBy({"numero_episode" = "ASC"})
     */
    private $episodes;

    public function __construct()
    {
        $this->acteurSaisons = new ArrayCollection();
        $this->episodes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    
    public function getNomComplet($vo){
        if(is_null($this->nom)){
            return $this->getSerie()->getTitreComplet($vo) . ' - Saison ' . $this->numero_saison;
        } else {
            return $this->getSerie()->getTitreComplet($vo) . ' - ' . $this->nom;
        }
    }

    public function getNumeroSaison(): ?int
    {
        return $this->numero_saison;
    }

    public function setNumeroSaison(int $numero_saison): self
    {
        $this->numero_saison = $numero_saison;

        return $this;
    }

    public function getNombreEpisode(): ?int
    {
        return $this->nombre_episode;
    }

    public function setNombreEpisode(int $nombre_episode): self
    {
        $this->nombre_episode = $nombre_episode;

        return $this;
    }

    public function getSerie(): ?Serie
    {
        return $this->serie;
    }

    public function setSerie(?Serie $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|ActeurSaison[]
     */
    public function getActeurSaisons(): Collection
    {
        return $this->acteurSaisons;
    }

    public function addActeurSaison(ActeurSaison $acteurSaison): self
    {
        if (!$this->acteurSaisons->contains($acteurSaison)) {
            $this->acteurSaisons[] = $acteurSaison;
            $acteurSaison->setSaison($this);
        }

        return $this;
    }

    public function removeActeurSaison(ActeurSaison $acteurSaison): self
    {
        if ($this->acteurSaisons->contains($acteurSaison)) {
            $this->acteurSaisons->removeElement($acteurSaison);
            // set the owning side to null (unless already changed)
            if ($acteurSaison->getSaison() === $this) {
                $acteurSaison->setSaison(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episodes->contains($episode)) {
            $this->episodes[] = $episode;
            $episode->setSaison($this);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        if ($this->episodes->contains($episode)) {
            $this->episodes->removeElement($episode);
            // set the owning side to null (unless already changed)
            if ($episode->getSaison() === $this) {
                $episode->setSaison(null);
            }
        }

        return $this;
    }
}

src/Controller/EpisodeController.php
<?php
namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Episode;
use App\Entity\Saison;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Form\EpisodeType;

class EpisodeController extends AppController
{

    /**
     * Liste des épisodes
     *
     * @Route("/episode/liste/{page}", name="episode_liste")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(SessionInterface $session, int $page = 1)
    {
        $repository = $this->getDoctrine()->getRepository(Episode::class);
        if ($session->get('user')['episode_vo']) {
            $order = 'Episode.titre_original';
        } else {
            $order = 'Episode.titre';
        }

        $params = array(
            'repository' => 'Episode',
            'orderBy' => array(
                $order => 'ASC'
            )
        );
        $episodes = $repository->findAllElements($page, self::MAX_RESULT, $params);

        $pagination = array(
            'page' => $page,
            'route' => 'episode_liste',
            'nbr_page' => ceil($episodes['total'] / self::MAX_RESULT),
            'total' => $episodes['total'],
            'route_params' => array()
        );

        $paths = array(
            'active' => 'Épisodes'
        );

        return $this->render('episode/index.html.twig', array(
            'episodes' => $episodes['paginator'],
            'pagination' => $pagination,
            'paths' => $paths
        ));
    }

    /**
     * Affichage d'un épisode
     *
     * @Route("/episode/{slug}/afficher/{page}", name="episode_afficher")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Episode $episode
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function afficher(Episode $episode, int $page = 1)
    {
        $paths = array(
            'home' => $this->homeURL(),
            'urls' => array(
                $this->generateUrl('episode_liste', array(
                    'page' => $page
                )) => 'Épisodes'
            ),
            'active' => 'Affichage' . $this->getIdNom($episode, 'episode')
        );

        return $this->render('episode/afficher.html.twig', array(
            'episode' => $episode,
            'page' => $page,
            'paths' => $paths
        ));
    }

    /**
     * Formulaire d'ajout d'un épisode
     *
     * @Route("/episode/ajouter/{page}", name="episode_ajouter")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Request $request
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function ajouter(Request $request, int $page = 1)
    {
        $episode = new Episode();

        $form = $this->createForm(EpisodeType::class, $episode);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $episode = $form->getData();

            $manager = $this->getDoctrine()->getManager();
            $slug = $this->createSlug($episode->getTitreOriginal(), 'Episode', array(
                $episode->getSaison()->getSerie()->getSlug(),
                'Saison_' . $episode->getSaison()->getNumeroSaison()
            ));
            $episode->setSlug($slug);

            $manager->persist($episode);
            $manager->flush();

            return $this->redirectToRoute('episode_afficher', array(
                'slug' => $episode->getSlug(),
                'page' => $page
            ));
        }

        $paths = array(
            'urls' => array(
                $this->generateUrl('episode_liste', array(
                    'page' => $page
                )) => 'Episodes'
            ),
            'active' => 'Ajouter un episode'
        );

        return $this->render('episode/ajouter.html.twig', array(
            'form' => $form->createView(),
            'page' => $page,
            'paths' => $paths
        ));
    }

    /**
     * Formulaire de modification d'un épisode
     *
     * @Route("/episode/{slug}/modifier/{page}", name="episode_modifier")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Request $request
     * @param Episode $episode
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function modifier(Request $request, Session $session, Episode $episode, int $page = 1)
    {
        $form = $this->createForm(EpisodeType::class, $episode);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $episode = $form->getData();

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($episode);
            $manager->flush();

            return $this->redirectToRoute('episode_afficher', array(
                'slug' => $episode->getSlug(),
                'page' => $page
            ));
        }

        $paths = array(
            'home' => $this->homeURL(),
            'urls' => array(
                $this->generateUrl('episode_liste', array(
                    'page' => $page
                )) => 'Episodes',
                $this->generateUrl('episode_afficher', array(
                    'slug' => $episode->getSlug(),
                    'page' => $page
                )) => $episode->getTitreComplet($session->get('user')['episode_vo'])
            ),
            'active' => 'Modification' . $this->getIdNom($episode, 'episode')
        );

        return $this->render('episode/modifier.html.twig', array(
            'form' => $form->createView(),
            'episode' => $episode,
            'page' => $page,
            'paths' => $paths
        ));
    }

    /**
     * Formulaire de suppression d'un episode
     *
     * @Route("/episode/supprimer/{slug}", name="episode_supprimer")
     * @IsGranted("ROLE_SUPER_ADMIN")
     *
     * @param Episode $episode
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function supprimer(Episode $episode)
    {
        $manager = $this->getDoctrine()->getManager();

        $episodePersonnes = $episode->getEpisodePersonnes();
        foreach ($episodePersonnes as $episodePersonne) {
            $manager->remove($episodePersonne);
        }

        $manager->remove($episode);
        $manager->flush();

        return $this->redirectToRoute('episode_liste');
    }

    /**
     * Affichage des épisodes d'une saison
     *
     * @Route("/episode/{slug}/afficher_saison", name="episode_saison_afficher")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Saison $saison
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function afficherPourSaison(Saison $saison)
    {
        return $this->render('episode/afficher_pour_saison.html.twig', array(
            'saison' => $saison,
            'episodes' => $saison->getEpisodes()
        ));
    }
}

templates/episode/afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ titre(episode, app.session.get('user')['episode_vo']) }} {% endblock %}

{% block body %}
	<div class="affichage">
		<div class="row display_element">
			<div class="col-sm center_img text-center">
				{{ image(episode.saison) | raw }}
			</div>
			<div class="col-sm center_img">
				<table class="middle">
            		<tr>
            			<th></th>
            			<td align="center">
            				{{ modifier(path('episode_modifier', {'slug': episode.slug, 'page': page})) | raw }}
                            {% if is_granted('ROLE_SUPER_ADMIN') %}
                                {{ supprimer(path('episode_supprimer', {'slug': episode.slug})) | raw }}
                            {% endif %}
            			</td>
            		</tr>
    				<tr>
        				<th>Série</th>
        				<td align=center>
        					<a href="{{ path('serie_afficher', {'slug': episode.saison.serie.slug}) }}">
        				        {{ titre(episode.saison.serie, app.session.get('user')['episode_vo']) }}
        					</a>
        				</td>
    				</tr>
    				<tr>
        				<th>Saison</th>
        				<td align=center>
        					<a href="{{ path('saison_afficher', {'slug': episode.saison.slug}) }}">
        						Saison {{ episode.saison.numeroSaison }}
        					</a>
        				</td>
    				</tr>
					{% if episode.titre is not null %}
        				<tr>
            				<th>Titre</th>
            				<td align=center>{{ episode.titre }}</td>
        				</tr>
    				{% endif %}
    				<tr>
        				<th>Titre Original</th>
        				<td align=center>{{ episode.titreOriginal }}</td>
    				</tr>
    				<tr>
        				<th>N° épisode</th>
        				<td align=center>{{ episode.numeroEpisode }}</td>
    				</tr>
    				<tr>
        				<th>N° de production</th>
        				<td align=center>{{ episode.numeroProduction }}</td>
    				</tr>
    				<tr>
        				<th>Première Diffusion</th>
        				<td align=center>{{ episode.premiereDiffusion | date('d/m/Y') }}</td>
    				</tr>
    				<tr>
        				<th>Durée</th>
        				<td align=center>{{ episode.duree }} min</td>
    				</tr>
				</table>
			</div>
		</div>
		<div class="row episode_header">
			<h5 class="col-12">
				Propriétaires: 
				<span id="add_personne" class="link"><span class="oi oi-plus"></span></span>
			</h5>
		</div>
		<div class="row" id="personnes">
			<div class="col-12 text-center">
				Chargement...
			</div>
		</div>
	</div>
    
    <div class="modal" tabindex="-1" role="dialog" id="bloc_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id ="modal_episode">
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
		$(document).ready(function(){
			Ajax("{{ path('personne_pour_episode', {'slug': episode.slug}) }}", "#personnes");
			$("#add_personne").click(function(){
				$("html").showLoading();
            	Ajax("{{ path('ajax_episode_personne_ajouter_personne', {'slug': episode.slug}) }}", "#modal_episode");
			});
		})
	</script>
{% endblock %}

templates/episode/afficher_pour_saison.html.twig
{% if saison.episodes is empty %}
	<div class="col-12 text-center">
		Aucun épisode n'est renseigné pour cette saison.
	</div>
{% else %}
	<table align="center" valign="middle">
		<tr align="center">
			<th>N° épisode</th>
			<th>Titre</th>
			<th>Durée (min)</th>
			<th>1ère diffusion</th>
		</tr>
		{% for episode in saison.episodes %}
			<tr align="center">
				<td>{{ episode.numeroEpisode }}</td>
				<td>
					<a href="{{ path('episode_afficher', {'slug': episode.slug}) }}">
						{{ titre(episode, app.session.get('user')['episode_vo']) }}
					</a>
				</td>
				<td>{{ episode.duree }}</td>
				<td>{{ episode.premiereDiffusion | date('d/m/Y') }}</td>
			</tr>
        {% endfor %}
        </table>
{% endif %}

templates/episode/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %} Episode - Ajout {% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="shadow-sm p-3 mb-5 bg-white rounded border">
        <div class="row">
        	<div class="col-sm-6 w-100">
                {{ form_row(form.saison) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.titre) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.titre_original) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.numero_episode) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.numero_production) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.duree) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.premiere_diffusion) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.description) }}
            </div>
    	</div>
        
        <div class="row text-center center-item">
            {{ form_row(form.save) }}
        </div>
    </div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
    
{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("#episode_saison").select2();
			$("#episode_premiere_diffusion select").select2();
		});
	</script>
{% endblock %}

templates/episode/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Épisodes{% endblock %}

{% block body %}
	<div class="card text-center">
        <div class="card-header text-left">
            {{ pagination.total }} épisode{% if pagination.total > 1 %}s{% endif %} {% if pagination.nbr_page > 0 %} - Page {{ pagination.page }} / {{ pagination.nbr_page }} {% endif %}
            {% if is_granted('ROLE_UTILISATEUR') %}
	            {{ ajouter(path('episode_ajouter'), "float-right marg-r-2") | raw }}
	        {% endif %}
        </div>
        <div class="card-body">
        	{% if episodes is empty %}
        		<div class="text-info text-center">Aucun épisode correspondant à la recherche.</div>
        	{% else %}
            	<table class="table table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Titre</th>
                            <th>Série - Saison</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for episode in episodes %}
                            <tr>
                                <td>{{ episode.id }}</td>
                                <td>
                                	<a href="{{ path('episode_afficher', {'slug': episode.slug}) | decode }}">
                                        {{ titre(episode, app.session.get('user')['episode_vo']) }}
                                    </a>
                                </td>
                                <td>{{ titre(episode.saison.serie, app.session.get('user')['episode_vo']) }} - Saison {{ episode.saison.numeroSaison }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
    			</table>
			{% endif %}
        </div>
        <div class="card-footer text-muted">
            {% include 'app/pagination.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/episode/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %} Episode - Modification {% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="shadow-sm p-3 mb-5 bg-white rounded border">
        <div class="row">
        	<div class="col-sm-6 w-100">
                {{ form_row(form.saison) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.titre) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.titre_original) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.numero_episode) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.numero_production) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.duree) }}
            </div>
        	<div class="col-sm">
                {{ form_row(form.premiere_diffusion) }}
            </div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm">
                {{ form_row(form.description) }}
            </div>
    	</div>
        
        <div class="row text-center center-item">
            {{ form_row(form.save) }}
        </div>
    </div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
    
{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("#episode_saison").select2();
			$("#episode_premiere_diffusion select").select2();
		});
	</script>
{% endblock %}