src/Entity/EpisodePersonne.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EpisodePersonneRepository")
 */
class EpisodePersonne
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_achat;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Personne", inversedBy="episodePersonnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personne;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Episode", inversedBy="episodePersonnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $episode;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieu", inversedBy="episodePersonnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lieu;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Format", inversedBy="episodePersonnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $format;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(?\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getPersonne(): ?Personne
    {
        return $this->personne;
    }

    public function setPersonne(?Personne $personne): self
    {
        $this->personne = $personne;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->episode;
    }

    public function setEpisode(?Episode $episode): self
    {
        $this->episode = $episode;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getFormat(): ?Format
    {
        return $this->format;
    }

    public function setFormat(?Format $format): self
    {
        $this->format = $format;

        return $this;
    }

}

src/Entity/Lieu.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LieuRepository")
 */
class Lieu
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;
    
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numero_voie;
    
    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $mention;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $voie;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;
    
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $code_postal;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Personne", mappedBy="lieu")
     */
    private $personnes;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EpisodePersonne", mappedBy="lieu")
     */
    private $episodePersonnes;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LivrePersonne", mappedBy="lieu")
     */
    private $livrePersonnes;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FilmPersonne", mappedBy="lieu")
     */
    private $filmPersonnes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Famille", mappedBy="lieux")
     */
    private $familles;

    public function __construct()
    {
        $this->personnes = new ArrayCollection();
        $this->episodePersonnes = new ArrayCollection();
        $this->livrePersonnes = new ArrayCollection();
        $this->filmPersonnes = new ArrayCollection();
        $this->familles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    
    public function getNomComplet(){
        return $this->nom;
    }

    public function getNumeroVoie(): ?int
    {
        return $this->numero_voie;
    }

    public function setNumeroVoie(?int $numero_voie): self
    {
        $this->numero_voie = $numero_voie;

        return $this;
    }

    public function getMention(): ?string
    {
        return $this->mention;
    }

    public function setMention(?string $mention): self
    {
        $this->mention = $mention;

        return $this;
    }

    public function getVoie(): ?string
    {
        return $this->voie;
    }

    public function setVoie(?string $voie): self
    {
        $this->voie = $voie;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }
    
    public function getAdresse(){
        $adresse = "";
        
        $adresse .= ($this->numero_voie ? $this->numero_voie : "");
        $adresse .= ($this->mention ? " " .$this->mention : "");
        $adresse .= ($this->numero_voie || $this->mention ? ", " : "");
        $adresse .= $this->voie . "<br>";
        $adresse .= $this->code_postal . " " . $this->ville;
        
        return $adresse;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setLieu($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->contains($personne)) {
            $this->personnes->removeElement($personne);
            // set the owning side to null (unless already changed)
            if ($personne->getLieu() === $this) {
                $personne->setLieu(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EpisodePersonne[]
     */
    public function getEpisodePersonnes(): Collection
    {
        return $this->episodePersonnes;
    }

    public function addEpisodePersonne(EpisodePersonne $episodePersonne): self
    {
        if (!$this->episodePersonnes->contains($episodePersonne)) {
            $this->episodePersonnes[] = $episodePersonne;
            $episodePersonne->setLieu($this);
        }

        return $this;
    }

    public function removeEpisodePersonne(EpisodePersonne $episodePersonne): self
    {
        if ($this->episodePersonnes->contains($episodePersonne)) {
            $this->episodePersonnes->removeElement($episodePersonne);
            // set the owning side to null (unless already changed)
            if ($episodePersonne->getLieu() === $this) {
                $episodePersonne->setLieu(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LivrePersonne[]
     */
    public function getLivrePersonnes(): Collection
    {
        return $this->livrePersonnes;
    }

    public function addLivrePersonne(LivrePersonne $livrePersonne): self
    {
        if (!$this->livrePersonnes->contains($livrePersonne)) {
            $this->livrePersonnes[] = $livrePersonne;
            $livrePersonne->setLieu($this);
        }

        return $this;
    }

    public function removeLivrePersonne(LivrePersonne $livrePersonne): self
    {
        if ($this->livrePersonnes->contains($livrePersonne)) {
            $this->livrePersonnes->removeElement($livrePersonne);
            // set the owning side to null (unless already changed)
            if ($livrePersonne->getLieu() === $this) {
                $livrePersonne->setLieu(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FilmPersonne[]
     */
    public function getFilmPersonnes(): Collection
    {
        return $this->filmPersonnes;
    }

    public function addFilmPersonne(FilmPersonne $filmPersonne): self
    {
        if (!$this->filmPersonnes->contains($filmPersonne)) {
            $this->filmPersonnes[] = $filmPersonne;
            $filmPersonne->setLieu($this);
        }

        return $this;
    }

    public function removeFilmPersonne(FilmPersonne $filmPersonne): self
    {
        if ($this->filmPersonnes->contains($filmPersonne)) {
            $this->filmPersonnes->removeElement($filmPersonne);
            // set the owning side to null (unless already changed)
            if ($filmPersonne->getLieu() === $this) {
                $filmPersonne->setLieu(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Famille[]
     */
    public function getFamilles(): Collection
    {
        return $this->familles;
    }

    public function addFamille(Famille $famille): self
    {
        if (!$this->familles->contains($famille)) {
            $this->familles[] = $famille;
            $famille->addLieux($this);
        }

        return $this;
    }

    public function removeFamille(Famille $famille): self
    {
        if ($this->familles->contains($famille)) {
            $this->familles->removeElement($famille);
            $famille->removeLieux($this);
        }

        return $this;
    }
}

src/Form/EpisodePersonneType.php
<?php
namespace App\Form;

use App\Entity\EpisodePersonne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Episode;
use App\Repository\EpisodeRepository;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\Format;
use App\Repository\FormatRepository;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use App\Entity\Personne;
use App\Entity\Lieu;

class EpisodePersonneType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['avec_personne']) {
            $builder->add('personne', EntityType::class, array(
                'class' => Personne::class,
                'choices' => $options['select_personne'],
                'choice_label' => function (Personne $p) {
                    if (! is_null($p->getNom()) && ! is_null($p->getPrenom())) {
                        return $p->getPrenom() . " " . $p->getNom();
                    } else {
                        return $p->getUsername();
                    }
                }
            ));
        }

        $builder->add('format', EntityType::class, array(
            'class' => Format::class,
            'query_builder' => function (FormatRepository $fr) {
                return $fr->createQueryBuilder('format')
                    ->andWhere('format.objet IN (0,2)')
                    ->orderBy('format.nom');
            },
            'choice_label' => 'nom'
        ))
            ->add('date_achat', DateType::class, array(
            'label' => "Date d'achat",
            'widget' => 'choice',
            'required' => false,
            'years' => range(date('Y') - 15, date('Y')),
            'format' => 'ddMMyyyy'
        ))
            ->add('lieu', EntityType::class, array(
            'class' => Lieu::class,
            'choices' => $options['select_lieu'],
            'choice_label' => 'nom'
        ));

        if ($options['avec_episode']) {
            if ($options['titre_vo']) {
                $builder->add('episode', EntityType::class, array(
                    'class' => Episode::class,
                    'query_builder' => function (EpisodeRepository $fr) {
                        return $fr->createQueryBuilder('episode')
                            ->orderBy('episode.titre_original');
                    },
                    'choice_label' => 'titre_original'
                ));
            } else {
                $builder->add('episode', EntityType::class, array(
                    'class' => Episode::class,
                    'query_builder' => function (EpisodeRepository $fr) {
                        return $fr->createQueryBuilder('episode')
                            ->orderBy('episode.titre');
                    },
                    'choice_label' => 'titre'
                ));
            }
        }

        if ($options['avec_save']) {
            $builder->add('save', SubmitType::class, array(
                'label' => $options['label_submit'],
                'attr' => array(
                    'class' => 'btn btn-media'
                )
            ));
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => EpisodePersonne::class,
            'label_submit' => 'Valider',
            'avec_save' => true,
            'select_personne' => array(),
            'select_lieu' => array(),
            'avec_personne' => true,
            'avec_episode' => true,
            'titre_vo' => true
        ));
    }
}

templates/episode_personne/afficher_proprios_episode.html.twig
{% if episodePersonnes is empty %}
	<div class="col-12 text-center">
		Personne ne possède cette épisode.
	</div>
{% else %}
	<table style="margin-left: 30px">
		{% for episodePersonne in episodePersonnes %}
			<tr align="center">
				<td>{{ episodePersonne.personne.username }}</td>
				<td>{{ episodePersonne.format.nom }}</td>
				<td>{{ episodePersonne.lieu.nom }}</td>
				<td>
					{% if episodePersonne.dateAchat is not null %}
				        {{ episodePersonne.dateAchat | date('d/m/Y') }}
				    {% endif %}
				</td>
				{% if is_granted('ROLE_UTILISATEUR') %}
					<td>
						<span id="edit_pers_{{ episodePersonne.id }}" class="link">
							<span class="oi oi-pencil"></span>
						</span>
						{% if is_granted('ROLE_ADMIN') or episodePersonne.personne.id == app.user.id %}
							<span id="delete_pers_{{ episodePersonne.id }}" class="link">
								<span class="oi oi-x"></span>
							</span>
						{% endif %}
					</td>
				{% endif %}
			</tr>
        {% endfor %}
        </table>
{% endif %}

{% block javascripts %}
	<script type="text/javascript">
		$(document).ready(function(){
			{% for episodePersonne in episodePersonnes %}
				var id = "#edit_pers_{{ episodePersonne.id }}";
    			$(id).click(function(){
    				$("html").showLoading();
                	Ajax("{{ path('ajax_episode_personne_editer_personne', {'id': episodePersonne.id}) }}", "#modal_episode");
    			});

    			var id_del = "#delete_pers_{{ episodePersonne.id }}";
    			$(id_del).click(function(){
        			var url = "{{ path('ajax_episode_personne_supprimer_personne', {'id': episodePersonne.id}) }}";
        			var url_base = "{{ path('personne_pour_episode', {'slug': episodePersonne.episode.slug}) }}";
        			deleteAjax(url, url_base, "#personnes");
    			});
			{% endfor %}
		})
	</script>
{% endblock %}

templates/episode_personne/ajax_ajouter_depuis_saison.html.twig
<div id="ajax_episode_personne_ajouter">
	<form name="episode_personne" method="post">
    <div class="modal-header">
        <h5 class="modal-title">Ajout d'un propriétaire à tous les épisodes de {{ titre(saison, app.session.get('user')['episode_vo']) }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <div class="row">
        	<div class="col-sm w-100">
            	<div class="form-group">
            		<label class="required" for="episode_personne_personne">Personne</label>
            		<select id="episode_personne_personne" name="episode_personne[personne]" class="form-control">
            			{% for personne in personnes %}
            				<option value="{{ personne.id }}">{{ personne.nomComplet }}</option>
            			{% endfor %}
            		</select>
            	</div>
            </div>
        	<div class="col-sm w-100">
            	<div class="form-group">
            		<label class="required" for="episode_personne_lieu">Lieu</label>
            		<select id="episode_personne_lieu" name="episode_personne[lieu]" class="form-control">
            			{% for lieu in lieux %}
            				<option value="{{ lieu.id }}">{{ lieu.nom }}</option>
            			{% endfor %}
            		</select>
            	</div>
            </div>
        </div>
        <div class="row">
        	<div class="col-sm w-100">
            	<div class="form-group">
            		<label class="required" for="episode_personne_format">Format</label>
            		<select id="episode_personne_format" name="episode_personne[format]" class="form-control">
            			{% for format in formats %}
            				<option value="{{ format.id }}">{{ format.nom }}</option>
            			{% endfor %}
            		</select>
            	</div>
            </div>
        	<div class="col-sm">
				<fieldset class="form-group">
					<legend class="col-form-label">Date d'achat</legend>
					<div id="episode_personne_date_achat" class="form-inline">
					<div class="sr-only">
                        <label class="" for="episode_personne_date_achat_year">Year</label>
                        <label class="" for="episode_personne_date_achat_month">Month</label>
                        <label class="" for="episode_personne_date_achat_day">Day</label>
            		</div>
            		<select id="episode_personne_date_achat_day" name="episode_personne[date_achat][day]" class="form-control">
            			<option value=""></option>
            			{% for i in 1..9 %}
            				<option value="{{ i }}">0{{ i }}</option>
            			{% endfor %}
            			{% for i in 10..31 %}
            				<option value="{{ i }}">{{ i }}</option>
            			{% endfor %}
            		</select>
            		<select id="episode_personne_date_achat_month" name="episode_personne[date_achat][month]" class="form-control">
            			<option value=""></option>
            			{% for i in 1..9 %}
            				<option value="{{ i }}">0{{ i }}</option>
            			{% endfor %}
            			{% for i in 10..12 %}
            				<option value="{{ i }}">{{ i }}</option>
            			{% endfor %}
            		</select>
            		<select id="episode_personne_date_achat_year" name="episode_personne[date_achat][year]" class="form-control">
            			<option value=""></option>
            			{% for i in date_debut..date_fin %}
            				<option value="{{ i }}">{{ i }}</option>
            			{% endfor %}
            		</select>
            	</fieldset>
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
    	<div class="form-group">
    		<button type="submit" id="episode_personne_save" name="episode_personne[save]" class="btn btn-media btn">
    			Valider
    		</button>
    	</div>
    </div>
    
    </form>
</div>

{% block javascripts %}
    <script type="text/javascript">
        $('#bloc_modal').modal({
            'show' : true,
            'backdrop' : 'static'
        });

        $("form select").select2({
        	minimumResultsForSearch: -1
        });

        var url = "{{ path('ajax_ajouter_depuis_saison', {'slug': saison.slug}) }}";
		var url_base = "{{ path('episode_saison_afficher', {'slug': saison.slug}) }}";
		SubmitModal("episode_personne", "saison", url, "#bloc_modal", url_base, "#saisons");
    </script>
{% endblock %}

templates/episode_personne/ajax_ajouter_personne.html.twig
<div id="ajax_episode_personne_ajouter">
	{{ form_start(form) }}
    <div class="modal-header">
        <h5 class="modal-title">Ajout d'un propriétaire à l'épisode {{ titre(episode, app.session.get('user')['episode_vo']) }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <div class="row">
        	<div class="col-sm w-100">
            	{{ form_row(form.personne) }}
            </div>
        	<div class="col-sm w-100">
            	{{ form_row(form.lieu) }}
            </div>
        </div>
        <div class="row">
        	<div class="col-sm w-100">
            	{{ form_row(form.format) }}
            </div>
        	<div class="col-sm">
            	{{ form_row(form.date_achat) }}
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
    	{{ form_row(form.save) }}
    </div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
</div>

{% block javascripts %}
    <script type="text/javascript">
        $('#bloc_modal').modal({
            'show' : true,
            'backdrop' : 'static'
        });

        $("form select").select2({
        	minimumResultsForSearch: -1
        });

        var url = "{{ path('ajax_episode_personne_ajouter_personne', {'slug': episode.slug}) }}";
		var url_base = "{{ path('personne_pour_episode', {'slug': episode.slug}) }}";
		SubmitModal("episode_personne", "episode", url, "#bloc_modal", url_base, "#personnes");
    </script>
{% endblock %}

templates/episode_personne/ajax_editer_personne.html.twig
<div id="ajax_episode_personne_editer">
	{{ form_start(form) }}
    <div class="modal-header">
        <h5 class="modal-title">Edition d'un propriétaire de l'épisode {{ titre(episodePersonne.episode, app.session.get('user')['episode_vo']) }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
    <div class="modal-body">
        <div class="row">
        	<div class="col-sm w-100">
            	{{ form_row(form.personne) }}
            </div>
        	<div class="col-sm w-100">
            	{{ form_row(form.lieu) }}
            </div>
        </div>
        <div class="row">
        	<div class="col-sm w-100">
            	{{ form_row(form.format) }}
            </div>
        	<div class="col-sm">
            	{{ form_row(form.date_achat) }}
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
    	{{ form_row(form.save) }}
    </div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
</div>

{% block javascripts %}
    <script type="text/javascript">
        $('#bloc_modal').modal({
            'show' : true,
            'backdrop' : 'static'
        });

        $("form select").select2({
        	minimumResultsForSearch: -1
        });

        var url = "{{ path('ajax_episode_personne_editer_personne', {'id': episodePersonne.id}) }}";
		var url_base = "{{ path('personne_pour_episode', {'slug': episodePersonne.episode.slug}) }}";
		SubmitModal("episode_personne", "episode", url, "#bloc_modal", url_base, "#personnes");
    </script>
{% endblock %}

templates/episode_personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/EpisodePersonneController.php'|file_link(0) }}">src/Controller/EpisodePersonneController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/episode_personne/index.html.twig'|file_link(0) }}">templates/episode_personne/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}