src/Entity/Acteur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActeurRepository")
 */
class Acteur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_usage;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_naissance;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_deces;
    
    /**
     * @ORM\Column(type="boolean")
     */
    private $sexe;
    
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Nationalite", inversedBy="acteurs")
     */
    private $nationalites;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Photo", inversedBy="acteurs")
     */
    private $photo;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActeurSaison", mappedBy="acteur")
     */
    private $acteurSaisons;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActeurFilm", mappedBy="acteur")
     */
    private $acteurFilms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Personne", mappedBy="acteur_favori")
     */
    private $personnes;

    public function __construct()
    {
        $this->nationalites = new ArrayCollection();
        $this->acteurSaisons = new ArrayCollection();
        $this->acteurFilms = new ArrayCollection();
        $this->personnes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNomUsage(): ?string
    {
        return $this->nom_usage;
    }

    public function setNomUsage(?string $nom_usage): self
    {
        $this->nom_usage = $nom_usage;

        return $this;
    }
    
    public function getNomComplet(){
        if(is_null($this->nom_usage)){
            if(!is_null($this->nom) && !is_null($this->prenom)){
                return $this->prenom . " " . $this->nom;
            } else if(!is_null($this->nom)){
                return $this->nom;
            } else if(!is_null($this->prenom)){
                return $this->prenom;
            }
        }
        return $this->nom_usage;
    }

    public function getNomNaissance(): ?string
    {
        return $this->nom_naissance;
    }

    public function setNomNaissance(?string $nom_naissance): self
    {
        $this->nom_naissance = $nom_naissance;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }
    
    public function getAnneeNaissance(): ?int
    {
        if(is_null($this->date_naissance)){
            return null;
        } else {
            return $this->date_naissance->format('Y');
        }
    }

    public function getDateDeces(): ?\DateTimeInterface
    {
        return $this->date_deces;
    }

    public function setDateDeces(?\DateTimeInterface $date_deces): self
    {
        $this->date_deces = $date_deces;

        return $this;
    }

    public function getSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    /**
     * @return Collection|Nationalite[]
     */
    public function getNationalites(): Collection
    {
        return $this->nationalites;
    }

    public function addNationalite(Nationalite $nationalite): self
    {
        if (!$this->nationalites->contains($nationalite)) {
            $this->nationalites[] = $nationalite;
        }

        return $this;
    }

    public function removeNationalite(Nationalite $nationalite): self
    {
        if ($this->nationalites->contains($nationalite)) {
            $this->nationalites->removeElement($nationalite);
        }

        return $this;
    }

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|ActeurSaison[]
     */
    public function getActeurSaisons(): Collection
    {
        return $this->acteurSaisons;
    }

    public function addActeurSaison(ActeurSaison $acteurSaison): self
    {
        if (!$this->acteurSaisons->contains($acteurSaison)) {
            $this->acteurSaisons[] = $acteurSaison;
            $acteurSaison->setActeur($this);
        }

        return $this;
    }

    public function removeActeurSaison(ActeurSaison $acteurSaison): self
    {
        if ($this->acteurSaisons->contains($acteurSaison)) {
            $this->acteurSaisons->removeElement($acteurSaison);
            // set the owning side to null (unless already changed)
            if ($acteurSaison->getActeur() === $this) {
                $acteurSaison->setActeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ActeurFilm[]
     */
    public function getActeurFilms(): Collection
    {
        return $this->acteurFilms;
    }

    public function addActeurFilm(ActeurFilm $acteurFilm): self
    {
        if (!$this->acteurFilms->contains($acteurFilm)) {
            $this->acteurFilms[] = $acteurFilm;
            $acteurFilm->setActeur($this);
        }

        return $this;
    }

    public function removeActeurFilm(ActeurFilm $acteurFilm): self
    {
        if ($this->acteurFilms->contains($acteurFilm)) {
            $this->acteurFilms->removeElement($acteurFilm);
            // set the owning side to null (unless already changed)
            if ($acteurFilm->getActeur() === $this) {
                $acteurFilm->setActeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setActeurFavori($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->contains($personne)) {
            $this->personnes->removeElement($personne);
            // set the owning side to null (unless already changed)
            if ($personne->getActeurFavori() === $this) {
                $personne->setActeurFavori(null);
            }
        }

        return $this;
    }
}

src/Form/ActeurType.php
<?php
namespace App\Form;

use App\Entity\Acteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use App\Form\newForm\SexeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Nationalite;
use App\Repository\NationaliteRepository;

class ActeurType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('prenom', TextType::class, array(
            'label' => 'Prénom',
            'required' => false
        ))
            ->add('nom', TextType::class, array(
            'label' => 'Nom',
            'required' => false
        ))
            ->add('nom_usage', TextType::class, array(
            'label' => "Nom d'usage",
            'required' => false
        ))
            ->add('nom_naissance', TextType::class, array(
            'label' => 'Nom de naissance',
            'required' => false
        ))
            ->add('date_naissance', BirthdayType::class, array(
            'label' => 'Date de naissance',
            'widget' => 'choice',
            'format' => 'dd/MM/yyyy',
            'required' => false
        ))
            ->add('sexe', SexeType::class)
            ->add('date_deces', BirthdayType::class, array(
            'label' => 'Date de décès',
            'widget' => 'choice',
            'format' => 'dd/MM/yyyy',
            'required' => false
        ))
            ->
        add('nationalites', EntityType::class, array(
            'class' => Nationalite::class,
            'choice_label' => 'feminin',
            'multiple' => true,
            'required' => false,
            'label' => 'Nationalité(s)',
            'attr' => array(
                'class' => 'multiple'
            ),
            'query_builder' => function (NationaliteRepository $nr) {
                return $nr->createQueryBuilder('n')
                    ->orderBy('n.pays');
            }
        ))
            ->add('save', SubmitType::class, array(
            'label' => $options['label_submit'],
            'attr' => array(
                'class' => 'btn btn-media'
            )
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Acteur::class,
            'allow_extra_fields' => true,
            'label_submit' => 'Enregistrer'
        ));
    }
}

src/Controller/ActeurController.php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Acteur;
use App\Form\ActeurType;

class ActeurController extends AppController
{
    /**
     * Liste des acteurs
     *
     * @Route("/acteur/liste/{page}", name="acteur_liste")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(int $page = 1)
    {
        $repository = $this->getDoctrine()->getRepository(Acteur::class);
        
        $params = array(
            'repository' => 'Acteur',
            'orderBy' => array(
                'Acteur.nom' => 'ASC',
                'Acteur.prenom' => 'ASC',
                'Acteur.nom_usage' => 'ASC'
            )
        );
        $acteurs = $repository->findAllElements($page, self::MAX_RESULT, $params);
        
        $pagination = array(
            'page' => $page,
            'route' => 'acteur_liste',
            'nbr_page' => ceil($acteurs['total'] / self::MAX_RESULT),
            'total' => $acteurs['total'],
            'route_params' => array()
        );
        
        $paths = array(
            'active' => 'Acteurs'
        );
        
        return $this->render('acteur/index.html.twig', array(
            'acteurs' => $acteurs['paginator'],
            'pagination' => $pagination,
            'paths' => $paths
        ));
    }
    
    /**
     * Affichage d'un acteur
     *
     * @Route("/acteur/{slug}/afficher/{page}", name="acteur_afficher")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Acteur $acteur
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function afficher(Acteur $acteur, int $page = 1)
    {
        $paths = array(
            'home' => $this->homeURL(),
            'urls' => array(
                $this->generateUrl('acteur_liste', array(
                    'page' => $page
                )) => 'Acteurs'
            ),
            'active' => 'Affichage' . $this->getIdNom($acteur, 'acteur')
        );
        
        return $this->render('acteur/afficher.html.twig', array(
            'acteur' => $acteur,
            'page' => $page,
            'paths' => $paths
        ));
    }
    
    /**
    * Formulaire d'ajout d'un acteur
    *
    * @Route("/acteur/ajouter/{page}", name="acteur_ajouter")
    * @IsGranted("ROLE_UTILISATEUR")
    *
    * @param Request $request
    * @param int $page
    * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
    */
    public function ajouter(Request $request, int $page = 1)
    {
        $acteur = new Acteur();
        
        $form = $this->createForm(ActeurType::class, $acteur);
        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $acteur = $form->getData();
            
            $manager = $this->getDoctrine()->getManager();
            
            $slug = $this->createSlug($acteur->getNomComplet(), 'Acteur', $acteur->getAnneeNaissance());
            $acteur->setSlug($slug);
            
            $manager->persist($acteur);
            $manager->flush();
            
            return $this->redirectToRoute('acteur_afficher', array(
                'slug' => $acteur->getSlug(),
                'page' => $page
            ));
        }
        
        $paths = array(
            'urls' => array(
                $this->generateUrl('acteur_liste', array(
                    'page' => $page
                )) => 'Acteurs'
            ),
            'active' => 'Ajouter un acteur'
        );
        
        return $this->render('acteur/ajouter.html.twig', array(
            'form' => $form->createView(),
            'page' => $page,
            'paths' => $paths
        ));
    }
    
    /**
     * Formulaire de modification d'un acteur
     *
     * @Route("/acteur/{slug}/modifier/{page}", name="acteur_modifier")
     * @IsGranted("ROLE_UTILISATEUR")
     *
     * @param Request $request
     * @param Acteur $acteur
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function modifier(Request $request, Acteur $acteur, int $page = 1)
    {
        $form = $this->createForm(ActeurType::class, $acteur);
        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $acteur = $form->getData();
            
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($acteur);
            $manager->flush();
            
            return $this->redirectToRoute('acteur_afficher', array(
                'slug' => $acteur->getSlug(),
                'page' => $page
            ));
        }
        
        $paths = array(
            'home' => $this->homeURL(),
            'urls' => array(
                $this->generateUrl('acteur_liste', array(
                    'page' => $page
                )) => 'Acteurs',
                $this->generateUrl('acteur_afficher', array(
                    'slug' => $acteur->getSlug(),
                    'page' => $page
                )) => $acteur->getNomComplet()
            ),
            'active' => 'Modification' . $this->getIdNom($acteur, 'acteur')
        );
        
        return $this->render('acteur/modifier.html.twig', array(
            'form' => $form->createView(),
            'acteur' => $acteur,
            'page' => $page,
            'paths' => $paths
        ));
    }
    
    /**
     * Formulaire de suppression d'un acteur
     *
     * @Route("/acteur/supprimer/{slug}", name="acteur_supprimer")
     * @IsGranted("ROLE_SUPER_ADMIN")
     *
     * @param Acteur $acteur
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function supprimer(Acteur $acteur){
        $manager = $this->getDoctrine()->getManager();
        
        $nationalites = $acteur->getNationalites();
        foreach ($nationalites as $nationalite){
            $acteur->removeNationalite($nationalite);
        }
        
        $acteurFilms = $acteur->getActeurFilms();
        foreach($acteurFilms as $acteurFilm){
            $manager->remove($acteurFilm);
        }
        
        $acteurSaisons = $acteur->getActeurSaisons();
        foreach($acteurSaisons as $acteurSaison){
            $manager->remove($acteurSaison);
        }
        
        $manager->persist($acteur);
        
        $manager->remove($acteur);
        $manager->flush();
        
        return $this->redirectToRoute('acteur_liste');
    }
}

templates/acteur/afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% if acteur.sexe == 1 %}Actrice{% else %}Acteur{% endif %} - {{ acteur.nomComplet }} {% endblock %}

{% block body %}
    <div class="affichage">
    	<div class="row display_element">
            <div class="col-sm center_img text-center">
            	{{ image(acteur) | raw }}
            </div>
            <div class="col-sm center_img">
				<table class="middle">
					{% if is_granted('ROLE_UTILISATEUR') %}
    					<tr>
    						<td></td>
    						<td align="center">
                                {{ modifier(path('acteur_modifier', {'slug': acteur.slug, 'page':page})) | raw }}
                                {% if is_granted('ROLE_SUPER_ADMIN') %}
                                    {{ supprimer(path('acteur_supprimer', {'slug': acteur.slug})) | raw }}
                                {% endif %}
                        	</td>
                    	</tr>
                    {% endif %}
					{% if acteur.prenom is not null %}
        				<tr>
            				<td>Prénom</td>
            				<td>{{ acteur.prenom }}</td>
        				</tr>
    				{% endif %}
					{% if acteur.nom is not null %}
    					<tr>
    						<td>Nom</td>
            				<td>{{ acteur.nom }}</td>
        				</tr>
    				{% endif %}
					{% if acteur.nomUsage is not null %}
        				<tr>
            				<td>Nom d'usage</td>
            				<td>{{ acteur.nomUsage }}</td>
        				</tr>
    				{% endif %}
					{% if acteur.nomNaissance is not null %}
        				<tr>
            				<td>Nom de naissance</td>
            				<td>{{ acteur.nomNaissance }}</td>
        				</tr>
    				{% endif %}
					{% if acteur.dateNaissance is not null %}
        				<tr>
            				<td>Date de naissance</td>
            				<td>{{ acteur.dateNaissance | date('d/m/Y') }}</td>
        				</tr>
        			{% endif %}
    				{% if acteur.dateDeces is not null %}
        				<tr>
            				<td>Date de décès</td>
            				<td>{{ acteur.dateDeces | date('d/m/Y') }}</td>
        				</tr>
    				{% endif %}
    				<tr>
        				<td>Sexe</td>
        				<td>{{ acteur.sexe | sexe }}</td>
    				</tr>
    				{% if acteur.nationalites is not null %}
        				<tr>
            				<td>Nationalité(s)</td>
            				<td>
            				    {% for nationalite in acteur.nationalites %}
            				    	{{ nationalite(nationalite, acteur.sexe) }}<br>
            				    {% endfor %}
            				</td>
        				</tr>
    				{% endif %}
				</table>
    		</div>
    	</div>
		<div class="row saison_header">
			<h5 class="col-12">
				Ses films: 
				<span id="edit_films" class="link"><span class="oi oi-pencil"></span></span>
			</h5>
		</div>
		<div class="row" id="films">
			<div class="col-12 text-center">
				Chargement...
			</div>
		</div>
		<div class="row saison_header">
			<h5 class="col-12">Ses séries:  
				<span id="edit_saisons" class="link"><span class="oi oi-pencil"></span></span>
			</h5>
		</div>
		<div class="row" id="saisons">
			<div class="col-12 text-center">
				Chargement...
			</div>
		</div>
    </div>
    
    <div class="modal" tabindex="-1" role="dialog" id="bloc_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id ="modal_acteur">
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
	<script src="{{ asset('js/collection.js') }}"></script>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function(){
        	Ajax("{{ path('film_pour_acteur', {'slug': acteur.slug}) | decode }}", "#films");
        	Ajax("{{ path('saison_pour_acteur', {'slug': acteur.slug}) | decode }}", "#saisons");
        	$("#edit_films").click(function(){
        		$("html").showLoading();
            	Ajax("{{ path('ajax_editer_films_acteur', {'slug': acteur.slug}) | decode }}", "#modal_acteur");
            });
        	$("#edit_saisons").click(function(){
        		$("html").showLoading();
            	Ajax("{{ path('ajax_editer_saisons_acteur', {'slug': acteur.slug}) |decode }}", "#modal_acteur");
            });
        });
    </script>
{% endblock %}

templates/acteur/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %} Acteur - Ajout {% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="shadow-sm p-3 mb-5 bg-white rounded border">
        <div class="row">
        	<div class="col-sm">
            	{{ form_row(form.prenom) }}
            </div>
        	<div class="col-sm">
            	{{ form_row(form.nom) }}
            </div>
        </div>
        <div class="row">
        	<div class="col-sm">
            	{{ form_row(form.nom_usage) }}
            </div>
            <div class="col-sm">
            	{{ form_row(form.nom_naissance) }}
            </div>
    	</div>
    	
    	<div class="row">
        	<div class="col-sm">
            	{{ form_row(form.date_naissance) }}
            </div>
            <div class="col-sm">
            	{{ form_row(form.date_deces) }}
            </div>
            <div class="col-sm">
        		<div id="sexe" class="w-100">
                    {{ form_row(form.sexe) }}
                </div>
        	</div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm w-100">
                    {{ form_row(form.nationalites) }}
                </div>
        </div>
        
    	<div class="row text-center center-item">
            {{ form_row(form.save) }}
        </div>
	</div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
{% endblock %}

{% block script %}
	<script src="{{ asset('js/select2.min.js') }}"></script>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $( document ).ready(function() {
			$("#acteur_nationalites").select2({
				"multiple": true
			});

			$("#acteur_sexe").select2({
			    minimumResultsForSearch: -1
			});

			$("#acteur_date_naissance select").select2();
			
			$("#acteur_date_deces select").select2();;
        });
    </script>
{% endblock %}

templates/acteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acteurs{% endblock %}

{% block body %}
	<div class="card text-center">
        <div class="card-header text-left">
            {{ pagination.total }} acteur{% if pagination.total > 1 %}s{% endif %} {% if pagination.nbr_page > 0 %} - Page {{ pagination.page }} / {{ pagination.nbr_page }} {% endif %}
            {% if is_granted('ROLE_UTILISATEUR') %}
	            {{ ajouter(path('acteur_ajouter'), "float-right marg-r-2") | raw }}
	        {% endif %}
        </div>
        <div class="card-body">
        	<div class="row">
        		{% if acteurs is empty %}
        			<div class="col-12 text-center">Il  n'y a aucun acteur correspondant à la recherche.</div>
        		{% else %}
            		{% for acteur in acteurs %}
                        <div class="col-img">
                            <div class="img-elt">
                            	<a href="{{ path('acteur_afficher', {'slug': acteur.slug, 'page': pagination.page}) | decode }}">
        						    {{ image(acteur) | raw }}<br>
        						    {{ acteur.nomComplet }}
        						</a>
    						</div>
                        </div>
                    {% endfor %}
                {% endif %}
        	</div>
        </div>
        <div class="card-footer text-muted">
            {% include 'app/pagination.html.twig' %}
        </div>
    </div>
{% endblock %}

templates/acteur/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %} Acteur - Modification {% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="shadow-sm p-3 mb-5 bg-white rounded border">
        <div class="row">
        	<div class="col-sm">
            	{{ form_row(form.prenom) }}
            </div>
        	<div class="col-sm">
            	{{ form_row(form.nom) }}
            </div>
        	<div class="col-sm">
            	{{ form_row(form.nom_usage) }}
            </div>
            <div class="col-sm">
            	{{ form_row(form.nom_naissance) }}
            </div>
    	</div>
    	
    	<div class="row">
        	<div class="col-sm">
            	{{ form_row(form.date_naissance) }}
            </div>
            <div class="col-sm">
            	{{ form_row(form.date_deces) }}
            </div>
            <div class="col-sm">
        		<div id="sexe" class="w-100">
                    {{ form_row(form.sexe) }}
                </div>
        	</div>
    	</div>
    	
        <div class="row">
        	<div class="col-sm w-100">
    			{{ form_row(form.nationalites) }}
    		</div>
        </div>
        
    	<div class="row text-center center-item">
            {{ form_row(form.save) }}
        </div>
	</div>
    
    {{ form_rest(form) }}
    {{ form_errors(form) }}
    {{ form_end(form) }}
    
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $( document ).ready(function() {
			$("#acteur_nationalites").select2({
				"multiple": true
			});

			$("#acteur_sexe").select2({
			    minimumResultsForSearch: -1
			});

			$("#acteur_date_naissance select").select2();
			
			$("#acteur_date_deces select").select2();;
        });
    </script>
{% endblock %}